version: '3.8'

services:
  app:
    build: .
    container_name: ibar_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo:latest
    container_name: ibar_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
