version: '3.8'

services:
  app:
    build: .
    container_name: ibar_app
    restart: always
    expose:
      - "5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    command: ["npm", "start"]

  nginx:
    image: nginx:alpine
    container_name: ibar_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
