version: '3.8'

services:
  app:
    build: .
    container_name: ibar_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
    command: ["npm", "start"]  
  mongo:
    image: mongo:latest
    container_name: ibar_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:alpine
    container_name: ibar_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongo_data:
